--DROP PROCEDURE IF EXISTS sp_fact_stock_receipts;
--CREATE PROCEDURE sp_fact_stock_receipts()
--BEGIN
--    DECLARE last_run DATETIME;
--    DECLARE current_run DATETIME;
--
--    SET current_run = NOW();
--
--    SELECT last_run_date INTO last_run
--    FROM icare_analytics.etl_process_history
--    WHERE process_name = 'fact_stock_receipts'
--    LIMIT 1;
--
--    IF last_run IS NULL THEN
--        SET last_run = '1900-01-01 00:00:00';
--    END IF;
--
--    CREATE TEMPORARY TABLE temp_latest_status AS
--    SELECT
--        sis.stock_invoice_id,
--        sis.status,
--        ROW_NUMBER() OVER (
--            PARTITION BY sis.stock_invoice_id
--            ORDER BY sis.date_created DESC
--        ) AS rn
--    FROM openmrs.st_stock_invoice_status sis
--    INNER JOIN openmrs.st_stock_invoice si
--        ON sis.stock_invoice_id = si.stock_invoice_id
--    WHERE
--        si.date_created >= last_run OR si.date_changed >= last_run;
--
--    REPLACE INTO icare_analytics.fact_stock_receipts
--    (
--        stock_invoice_item_id, invoice_id, invoice_number, receiving_date,
--        supplier_id, item_id, batch_no, expiry_date, uom_concept_id,
--        batch_quantity, unit_price, total_amount, location_id,
--        current_status, date_created, uuid
--    )
--    SELECT
--        sii.stock_invoice_item_id,
--        si.stock_invoice_id,
--        si.invoice_number,
--        si.receiving_date,
--        si.supplier_id,
--        sii.item_id,
--        sii.batch_no,
--        sii.expiry_date,
--        sii.uom,
--        sii.batch_quantity,
--        sii.unit_price,
--        sii.amount,
--        sii.location_id,
--        tls.status AS current_status,
--        sii.date_created,
--        sii.uuid
--    FROM
--        openmrs.st_stock_invoice_item sii
--    INNER JOIN
--        openmrs.st_stock_invoice si
--        ON sii.stock_invoice_id = si.stock_invoice_id
--    LEFT JOIN
--        temp_latest_status tls
--        ON si.stock_invoice_id = tls.stock_invoice_id AND tls.rn = 1
--    WHERE
--        sii.voided = 0 AND si.voided = 0 AND
--        (sii.date_created >= last_run OR sii.date_changed >= last_run);
--
--    DROP TEMPORARY TABLE temp_latest_status;
--
--    REPLACE INTO icare_analytics.etl_process_history (process_name, last_run_date, status)
--    VALUES ('fact_stock_receipts', current_run, 'SUCCESS');
--
--END;